//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.26 at 10:59:59 AM HST 
//


package org.hackystat.sensorshell.usermap.resource.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{}password"/>
 *       &lt;attribute ref="{}sensorbase"/>
 *       &lt;attribute ref="{}toolaccount"/>
 *       &lt;attribute ref="{}user"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "user")
public class User {

    @XmlAttribute
    protected String password;
    @XmlAttribute
    protected String sensorbase;
    @XmlAttribute
    protected String toolaccount;
    @XmlAttribute
    protected String user;

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the sensorbase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorbase() {
        return sensorbase;
    }

    /**
     * Sets the value of the sensorbase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorbase(String value) {
        this.sensorbase = value;
    }

    /**
     * Gets the value of the toolaccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolaccount() {
        return toolaccount;
    }

    /**
     * Sets the value of the toolaccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolaccount(String value) {
        this.toolaccount = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

}
